"""update knowledge

Revision ID: 5260a3b527ef
Revises: d474d7f22523
Create Date: 2026-04-17 04:00:40.732229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5260a3b527ef'
down_revision: Union[str, Sequence[str], None] = 'd474d7f22523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='personal/shared'),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True, comment='知识库归属用户ID'),
    sa.Column('creator_user_id', sa.String(length=32), nullable=False, comment='创建人ID'),
    sa.Column('is_active', sa.SmallInteger(), nullable=False, comment='是否启用(1启用,0停用)'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base'))
    )
    op.create_index(op.f('ix_knowledge_base_creator_user_id'), 'knowledge_base', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_name'), 'knowledge_base', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_base_owner_user_id'), 'knowledge_base', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_scope'), 'knowledge_base', ['scope'], unique=False)
    op.create_table('knowledge_file',
    sa.Column('kb_id', sa.String(length=32), nullable=False, comment='知识库ID'),
    sa.Column('folder_id', sa.String(length=32), nullable=True, comment='文件夹ID，可空表示知识库根目录'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='显示文件名'),
    sa.Column('file_ext', sa.String(length=20), nullable=False, comment='文件扩展名'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='本地存储路径'),
    sa.Column('parse_status', sa.String(length=20), nullable=False, comment='pending/processing/success/failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='切块数'),
    sa.Column('uploaded_by', sa.String(length=32), nullable=False, comment='上传人ID'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_file'))
    )
    op.create_index(op.f('ix_knowledge_file_file_name'), 'knowledge_file', ['file_name'], unique=False)
    op.create_index(op.f('ix_knowledge_file_folder_id'), 'knowledge_file', ['folder_id'], unique=False)
    op.create_index(op.f('ix_knowledge_file_kb_id'), 'knowledge_file', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_file_parse_status'), 'knowledge_file', ['parse_status'], unique=False)
    op.create_index(op.f('ix_knowledge_file_uploaded_by'), 'knowledge_file', ['uploaded_by'], unique=False)
    op.create_table('knowledge_folder',
    sa.Column('kb_id', sa.String(length=32), nullable=False, comment='知识库ID'),
    sa.Column('parent_id', sa.String(length=32), nullable=True, comment='父文件夹ID，当前可先不使用'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='文件夹名称'),
    sa.Column('creator_user_id', sa.String(length=32), nullable=False, comment='创建人ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_active', sa.SmallInteger(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_folder'))
    )
    op.create_index(op.f('ix_knowledge_folder_creator_user_id'), 'knowledge_folder', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_folder_kb_id'), 'knowledge_folder', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_folder_name'), 'knowledge_folder', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_folder_parent_id'), 'knowledge_folder', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_parent_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sequence_no'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('knowledge_folders')
    op.drop_index(op.f('ix_knowledge_chunks_file_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_folder_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_knowledge_files_ext'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_folder_id'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_status'), table_name='knowledge_files')
    op.drop_table('knowledge_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_files',
    sa.Column('folder_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='文件夹ID'),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='原始文件名'),
    sa.Column('ext', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='扩展名'),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='MIME类型'),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False, comment='文件字节数'),
    sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='文件存储路径'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='文件状态: pending/parsing/ready/failed'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='错误信息'),
    sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='切块数量'),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_files'))
    )
    op.create_index(op.f('ix_knowledge_files_status'), 'knowledge_files', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_files_folder_id'), 'knowledge_files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_knowledge_files_ext'), 'knowledge_files', ['ext'], unique=False)
    op.create_table('chat_threads',
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='线程标题'),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True, comment='历史摘要'),
    sa.Column('summary_version', sa.INTEGER(), autoincrement=False, nullable=False, comment='摘要版本'),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='消息数'),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='最后消息时间'),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_threads'))
    )
    op.create_table('knowledge_chunks',
    sa.Column('file_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='文件ID'),
    sa.Column('folder_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='文件夹ID'),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False, comment='切块序号'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='文本内容'),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='页码、sheet等元信息'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False, comment='向量'),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    op.create_index(op.f('ix_knowledge_chunks_folder_id'), 'knowledge_chunks', ['folder_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_file_id'), 'knowledge_chunks', ['file_id'], unique=False)
    op.create_table('knowledge_folders',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='文件夹名称'),
    sa.Column('sort_no', sa.INTEGER(), autoincrement=False, nullable=False, comment='排序号'),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_folders'))
    )
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='线程ID'),
    sa.Column('parent_message_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='父消息ID'),
    sa.Column('sequence_no', sa.INTEGER(), autoincrement=False, nullable=False, comment='线程内顺序号'),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='user/assistant/system'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='消息内容'),
    sa.Column('tokens_estimate', sa.INTEGER(), autoincrement=False, nullable=False, comment='粗略token数'),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='引用来源等'),
    sa.Column('is_summarized', sa.INTEGER(), autoincrement=False, nullable=False, comment='是否已汇总 0/1'),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sequence_no'), 'chat_messages', ['sequence_no'], unique=False)
    op.create_index(op.f('ix_chat_messages_parent_message_id'), 'chat_messages', ['parent_message_id'], unique=False)
    op.drop_index(op.f('ix_knowledge_folder_parent_id'), table_name='knowledge_folder')
    op.drop_index(op.f('ix_knowledge_folder_name'), table_name='knowledge_folder')
    op.drop_index(op.f('ix_knowledge_folder_kb_id'), table_name='knowledge_folder')
    op.drop_index(op.f('ix_knowledge_folder_creator_user_id'), table_name='knowledge_folder')
    op.drop_table('knowledge_folder')
    op.drop_index(op.f('ix_knowledge_file_uploaded_by'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_parse_status'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_kb_id'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_folder_id'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_file_name'), table_name='knowledge_file')
    op.drop_table('knowledge_file')
    op.drop_index(op.f('ix_knowledge_base_scope'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_owner_user_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_name'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_creator_user_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
