"""init model

Revision ID: 665d5d0632eb
Revises: 
Create Date: 2026-04-14 21:21:57.983293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '665d5d0632eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='用户名'),
    sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='昵称'),
    sa.Column('phone', sa.VARCHAR(length=11), autoincrement=False, nullable=False, comment='手机号'),
    sa.Column('hashed_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='加密后的密码'),
    sa.Column('is_active', sa.SMALLINT(), autoincrement=False, nullable=False, comment='\t是否活跃 (1: 正常/活跃, 0: 禁用/不活跃)'),
    sa.Column('role_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='角色ID'),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_role',
    sa.Column('role_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='角色名称'),
    sa.Column('role_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='角色权限字符串 '),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role'))
    )
    # ### end Alembic commands ###
