"""remove knowledge_base.description

Revision ID: 6aadf6767ee3
Revises: 5260a3b527ef
Create Date: 2026-04-17 04:08:34.152149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aadf6767ee3'
down_revision: Union[str, Sequence[str], None] = '5260a3b527ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='知识库描述'))
    # ### end Alembic commands ###
