"""update knowledge ids str32 to str100

Revision ID: 6f32e85c528a
Revises: 6aadf6767ee3
Create Date: 2026-04-17 16:19:25.440271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f32e85c528a'
down_revision: Union[str, Sequence[str], None] = '6aadf6767ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'owner_user_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='知识库归属用户ID',
               existing_nullable=True)
    op.alter_column('knowledge_base', 'creator_user_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='创建人ID',
               existing_nullable=False)
    op.alter_column('knowledge_file', 'kb_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='知识库ID',
               existing_nullable=False)
    op.alter_column('knowledge_file', 'folder_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='文件夹ID，可空表示知识库根目录',
               existing_nullable=True)
    op.alter_column('knowledge_file', 'uploaded_by',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='上传人ID',
               existing_nullable=False)
    op.alter_column('knowledge_folder', 'kb_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='知识库ID',
               existing_nullable=False)
    op.alter_column('knowledge_folder', 'parent_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='父文件夹ID，当前可先不使用',
               existing_nullable=True)
    op.alter_column('knowledge_folder', 'creator_user_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_comment='创建人ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_folder', 'creator_user_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='创建人ID',
               existing_nullable=False)
    op.alter_column('knowledge_folder', 'parent_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='父文件夹ID，当前可先不使用',
               existing_nullable=True)
    op.alter_column('knowledge_folder', 'kb_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='知识库ID',
               existing_nullable=False)
    op.alter_column('knowledge_file', 'uploaded_by',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='上传人ID',
               existing_nullable=False)
    op.alter_column('knowledge_file', 'folder_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='文件夹ID，可空表示知识库根目录',
               existing_nullable=True)
    op.alter_column('knowledge_file', 'kb_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='知识库ID',
               existing_nullable=False)
    op.alter_column('knowledge_base', 'creator_user_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='创建人ID',
               existing_nullable=False)
    op.alter_column('knowledge_base', 'owner_user_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_comment='知识库归属用户ID',
               existing_nullable=True)
    # ### end Alembic commands ###
