"""init1

Revision ID: b7ed30c31b72
Revises: 2bd8228562d4
Create Date: 2026-04-16 02:22:31.739060

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7ed30c31b72'
down_revision: Union[str, Sequence[str], None] = '2bd8228562d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.String(length=36), nullable=False, comment='线程ID'),
    sa.Column('parent_message_id', sa.String(length=36), nullable=True, comment='父消息ID'),
    sa.Column('sequence_no', sa.Integer(), nullable=False, comment='线程内顺序号'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('tokens_estimate', sa.Integer(), nullable=False, comment='粗略token数'),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='引用来源等'),
    sa.Column('is_summarized', sa.Integer(), nullable=False, comment='是否已汇总 0/1'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_parent_message_id'), 'chat_messages', ['parent_message_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sequence_no'), 'chat_messages', ['sequence_no'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('title', sa.String(length=200), nullable=False, comment='线程标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='历史摘要'),
    sa.Column('summary_version', sa.Integer(), nullable=False, comment='摘要版本'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息数'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='最后消息时间'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_threads'))
    )
    op.create_table('knowledge_chunks',
    sa.Column('file_id', sa.String(length=36), nullable=False, comment='文件ID'),
    sa.Column('folder_id', sa.String(length=36), nullable=True, comment='文件夹ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='切块序号'),
    sa.Column('content', sa.Text(), nullable=False, comment='文本内容'),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='页码、sheet等元信息'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False, comment='向量'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    op.create_index(op.f('ix_knowledge_chunks_file_id'), 'knowledge_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_folder_id'), 'knowledge_chunks', ['folder_id'], unique=False)
    op.create_table('knowledge_files',
    sa.Column('folder_id', sa.String(length=36), nullable=True, comment='文件夹ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('ext', sa.String(length=20), nullable=False, comment='扩展名'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('size', sa.Integer(), nullable=False, comment='文件字节数'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='文件状态: pending/parsing/ready/failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='切块数量'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_files'))
    )
    op.create_index(op.f('ix_knowledge_files_ext'), 'knowledge_files', ['ext'], unique=False)
    op.create_index(op.f('ix_knowledge_files_folder_id'), 'knowledge_files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_knowledge_files_status'), 'knowledge_files', ['status'], unique=False)
    op.create_table('knowledge_folders',
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父级文件夹ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='文件夹名称'),
    sa.Column('sort_no', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_folders'))
    )
    op.create_index(op.f('ix_knowledge_folders_parent_id'), 'knowledge_folders', ['parent_id'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('hashed_password', sa.String(length=100), nullable=False, comment='加密后的密码'),
    sa.Column('is_active', sa.SmallInteger(), nullable=False, comment='\t是否活跃 (1: 正常/活跃, 0: 禁用/不活跃)'),
    sa.Column('role_id', sa.String(length=100), nullable=False, comment='角色ID'),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_role',
    sa.Column('role_name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('role_key', sa.String(length=100), nullable=False, comment='角色权限字符串 '),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=False, comment='是否删除(0: 正常, 1: 删除)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('role_key', name=op.f('uq_user_role_role_key')),
    sa.UniqueConstraint('role_name', name=op.f('uq_user_role_role_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_knowledge_folders_parent_id'), table_name='knowledge_folders')
    op.drop_table('knowledge_folders')
    op.drop_index(op.f('ix_knowledge_files_status'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_folder_id'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_ext'), table_name='knowledge_files')
    op.drop_table('knowledge_files')
    op.drop_index(op.f('ix_knowledge_chunks_folder_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_file_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sequence_no'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_parent_message_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
