"""remove knowledge.parent_id

Revision ID: d474d7f22523
Revises: b7ed30c31b72
Create Date: 2026-04-16 03:59:34.673544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd474d7f22523'
down_revision: Union[str, Sequence[str], None] = 'b7ed30c31b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_folders_parent_id'), table_name='knowledge_folders')
    op.drop_column('knowledge_folders', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_folders', sa.Column('parent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='父级文件夹ID'))
    op.create_index(op.f('ix_knowledge_folders_parent_id'), 'knowledge_folders', ['parent_id'], unique=False)
    # ### end Alembic commands ###
